repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    files: ^.*\.(py|md|yml)$
    exclude: >
      (?x)^(
        src/test/fuzzy_test.py|
        src/test/alg_test.py
      )$
    additional_dependencies:
    - tomli
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.10
  hooks:
  - id: ruff-check
    args:
      - --fix
      - --unsafe-fixes
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/pycqa/pylint
  rev: v3.3.8
  hooks:
  - id: pylint
    args:
    - -d import-error
    - -sn
- repo: https://github.com/pre-commit/mirrors-mypy
  # pinned due to
  # https://github.com/python/typeshed/pull/9771 and
  # https://github.com/python/mypy/issues/15257 for DaskCollection.__dask_scheduler__
  rev: v1.15.0
  hooks:
  - id: mypy
    # Override default --ignore-missing-imports
    # Use pyproject.toml if possible instead of adding command line parameters here
    args: [--warn-unused-configs]
    additional_dependencies:
      # Type stubs
      # - pandas-stubs  # TODO
      - types-docutils
      - types-PyYAML
      - types-psutil
      - types-requests
      - types-setuptools
      # Typed libraries
      - numpy
      - pytest
