name: Run Tests

on:
  pull_request_review:
    types: [submitted, edited]
  workflow_dispatch:

jobs:
  pylint:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    uses: ./.github/workflows/define-pylint.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  pytest:
    needs: pylint
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    uses: ./.github/workflows/define-pytest.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit
