name: Run tests

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  pylint:
    strategy:
      matrix:
        python-version: ["3.14"]
    uses: ./.github/workflows/define-pylint.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  mypy:
    strategy:
      matrix:
        python-version: ["3.14"]
    uses: ./.github/workflows/define-mypy.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  pytest:
    strategy:
      matrix:
        python-version: ["3.11", "3.14"]
    uses: ./.github/workflows/define-pytest.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit
